// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_locks.sql

package statestore

import (
	"context"
)

const clearAdminLock = `-- name: ClearAdminLock :exec
DELETE FROM admin_locks
WHERE sub = ?1
`

func (q *Queries) ClearAdminLock(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, clearAdminLock, sub)
	return err
}

const createAdminLock = `-- name: CreateAdminLock :exec
INSERT INTO admin_locks (sub, created_at)
VALUES (?1, ?2)
ON CONFLICT (sub) DO NOTHING
`

type CreateAdminLockParams struct {
	Sub       string
	CreatedAt string
}

func (q *Queries) CreateAdminLock(ctx context.Context, arg CreateAdminLockParams) error {
	_, err := q.db.ExecContext(ctx, createAdminLock, arg.Sub, arg.CreatedAt)
	return err
}

const getAdminLock = `-- name: GetAdminLock :one
SELECT sub, created_at
FROM admin_locks
WHERE sub = ?1
`

func (q *Queries) GetAdminLock(ctx context.Context, sub string) (AdminLock, error) {
	row := q.db.QueryRowContext(ctx, getAdminLock, sub)
	var i AdminLock
	err := row.Scan(&i.Sub, &i.CreatedAt)
	return i, err
}
