// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_records.sql

package statestore

import (
	"context"
	"database/sql"
)

const createAuditRecord = `-- name: CreateAuditRecord :exec
INSERT INTO audit_records (
    id,
    created_at,
    category,
    sub,
    details
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateAuditRecordParams struct {
	ID        string
	CreatedAt string
	Category  string
	Sub       sql.NullString
	Details   string
}

func (q *Queries) CreateAuditRecord(ctx context.Context, arg CreateAuditRecordParams) error {
	_, err := q.db.ExecContext(ctx, createAuditRecord,
		arg.ID,
		arg.CreatedAt,
		arg.Category,
		arg.Sub,
		arg.Details,
	)
	return err
}

const deleteAuditRecordsBefore = `-- name: DeleteAuditRecordsBefore :execrows
DELETE FROM audit_records
WHERE created_at <= ?1
`

func (q *Queries) DeleteAuditRecordsBefore(ctx context.Context, before string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditRecordsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAuditRecords = `-- name: ListAuditRecords :many
SELECT id, created_at, category, sub, details
FROM audit_records
ORDER BY created_at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListAuditRecords(ctx context.Context, limit int64) ([]AuditRecord, error) {
	rows, err := q.db.QueryContext(ctx, listAuditRecords, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditRecord
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.Sub,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
