// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package statestore

import (
	"database/sql"
)

type AdminLock struct {
	Sub       string
	CreatedAt string
}

type AuditRecord struct {
	ID        string
	CreatedAt string
	Category  string
	Sub       sql.NullString
	Details   string
}

type OneUseToken struct {
	ID            string
	SecretHash    []byte
	Sub           string
	TotpRev       int64
	ExpiresAt     string
	ConsumedAt    sql.NullString
	CreatedAt     string
	ClientID      sql.NullString
	RedirectUri   sql.NullString
	Scope         sql.NullString
	Nonce         sql.NullString
	PkceChallenge sql.NullString
	PkceMethod    sql.NullString
}

type PanicLock struct {
	Sub       string
	CreatedAt string
}

type RateLimitCounter struct {
	Key       string
	Attempts  int64
	ResetAt   string
	UpdatedAt string
}

type Session struct {
	ID         string
	SecretHash []byte
	Sub        string
	TotpRev    int64
	CreatedAt  string
	ExpiresAt  string
	IpAddress  sql.NullString
	UserAgent  sql.NullString
}
