// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: one_use_tokens.sql

package statestore

import (
	"context"
	"database/sql"
)

const consumeOneUseToken = `-- name: ConsumeOneUseToken :execrows
UPDATE one_use_tokens
SET consumed_at = ?1
WHERE id = ?2
  AND consumed_at IS NULL
`

type ConsumeOneUseTokenParams struct {
	ConsumedAt sql.NullString
	ID         string
}

func (q *Queries) ConsumeOneUseToken(ctx context.Context, arg ConsumeOneUseTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeOneUseToken, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOneUseToken = `-- name: CreateOneUseToken :exec
INSERT INTO one_use_tokens (
    id,
    kind,
    secret_hash,
    sub,
    totp_rev,
    expires_at,
    created_at,
    code_client_id,
    code_redirect_uri,
    code_scope,
    code_nonce,
    code_pkce_challenge,
    code_pkce_method,
    code_auth_time
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14
)
`

type CreateOneUseTokenParams struct {
	ID                string
	Kind              string
	SecretHash        []byte
	Sub               string
	TotpRev           int64
	ExpiresAt         string
	CreatedAt         string
	CodeClientID      sql.NullString
	CodeRedirectUri   sql.NullString
	CodeScope         sql.NullString
	CodeNonce         sql.NullString
	CodePkceChallenge sql.NullString
	CodePkceMethod    sql.NullString
	CodeAuthTime      sql.NullString
}

func (q *Queries) CreateOneUseToken(ctx context.Context, arg CreateOneUseTokenParams) error {
	_, err := q.db.ExecContext(ctx, createOneUseToken,
		arg.ID,
		arg.Kind,
		arg.SecretHash,
		arg.Sub,
		arg.TotpRev,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.CodeClientID,
		arg.CodeRedirectUri,
		arg.CodeScope,
		arg.CodeNonce,
		arg.CodePkceChallenge,
		arg.CodePkceMethod,
		arg.CodeAuthTime,
	)
	return err
}

const deleteExpiredOneUseTokens = `-- name: DeleteExpiredOneUseTokens :execrows
DELETE FROM one_use_tokens
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredOneUseTokens(ctx context.Context, now string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOneUseTokens, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOneUseToken = `-- name: DeleteOneUseToken :exec
DELETE FROM one_use_tokens
WHERE id = ?1
`

func (q *Queries) DeleteOneUseToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOneUseToken, id)
	return err
}

const getOneUseToken = `-- name: GetOneUseToken :one
SELECT id, kind, secret_hash, sub, totp_rev, expires_at, consumed_at, created_at,
       code_client_id, code_redirect_uri, code_scope, code_nonce,
       code_pkce_challenge, code_pkce_method, code_auth_time
FROM one_use_tokens
WHERE id = ?1
`

func (q *Queries) GetOneUseToken(ctx context.Context, id string) (OneUseToken, error) {
	row := q.db.QueryRowContext(ctx, getOneUseToken, id)
	var i OneUseToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SecretHash,
		&i.Sub,
		&i.TotpRev,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.CodeClientID,
		&i.CodeRedirectUri,
		&i.CodeScope,
		&i.CodeNonce,
		&i.CodePkceChallenge,
		&i.CodePkceMethod,
		&i.CodeAuthTime,
	)
	return i, err
}
