// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: one_use_tokens.sql

package statestore

import (
	"context"
	"database/sql"
)

const consumeOneUseToken = `-- name: ConsumeOneUseToken :execrows
UPDATE one_use_tokens
SET consumed_at = ?1
WHERE id = ?2
  AND consumed_at IS NULL
`

type ConsumeOneUseTokenParams struct {
	ConsumedAt sql.NullString
	ID         string
}

func (q *Queries) ConsumeOneUseToken(ctx context.Context, arg ConsumeOneUseTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeOneUseToken, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOneUseToken = `-- name: CreateOneUseToken :exec
INSERT INTO one_use_tokens (
    id,
    secret_hash,
    sub,
    totp_rev,
    expires_at,
    created_at,
    client_id,
    redirect_uri,
    scope,
    nonce,
    pkce_challenge,
    pkce_method
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
)
`

type CreateOneUseTokenParams struct {
	ID            string
	SecretHash    []byte
	Sub           string
	TotpRev       int64
	ExpiresAt     string
	CreatedAt     string
	ClientID      sql.NullString
	RedirectUri   sql.NullString
	Scope         sql.NullString
	Nonce         sql.NullString
	PkceChallenge sql.NullString
	PkceMethod    sql.NullString
}

func (q *Queries) CreateOneUseToken(ctx context.Context, arg CreateOneUseTokenParams) error {
	_, err := q.db.ExecContext(ctx, createOneUseToken,
		arg.ID,
		arg.SecretHash,
		arg.Sub,
		arg.TotpRev,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scope,
		arg.Nonce,
		arg.PkceChallenge,
		arg.PkceMethod,
	)
	return err
}

const deleteExpiredOneUseTokens = `-- name: DeleteExpiredOneUseTokens :execrows
DELETE FROM one_use_tokens
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredOneUseTokens(ctx context.Context, now string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOneUseTokens, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOneUseToken = `-- name: DeleteOneUseToken :exec
DELETE FROM one_use_tokens
WHERE id = ?1
`

func (q *Queries) DeleteOneUseToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOneUseToken, id)
	return err
}

const getOneUseToken = `-- name: GetOneUseToken :one
SELECT id, secret_hash, sub, totp_rev, expires_at, consumed_at, created_at,
       client_id, redirect_uri, scope, nonce, pkce_challenge, pkce_method
FROM one_use_tokens
WHERE id = ?1
`

func (q *Queries) GetOneUseToken(ctx context.Context, id string) (OneUseToken, error) {
	row := q.db.QueryRowContext(ctx, getOneUseToken, id)
	var i OneUseToken
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Sub,
		&i.TotpRev,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.Nonce,
		&i.PkceChallenge,
		&i.PkceMethod,
	)
	return i, err
}
