// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: one_use_tokens.sql

package statestore

import (
	"context"
	"database/sql"
)

const consumeOneUseToken = `-- name: ConsumeOneUseToken :exec
UPDATE one_use_tokens
SET consumed_at = ?1
WHERE id = ?2
  AND consumed_at IS NULL
`

type ConsumeOneUseTokenParams struct {
	ConsumedAt sql.NullString
	ID         string
}

func (q *Queries) ConsumeOneUseToken(ctx context.Context, arg ConsumeOneUseTokenParams) error {
	_, err := q.db.ExecContext(ctx, consumeOneUseToken, arg.ConsumedAt, arg.ID)
	return err
}

const createOneUseToken = `-- name: CreateOneUseToken :exec
INSERT INTO one_use_tokens (
    id,
    secret_hash,
    sub,
    totp_rev,
    expires_at,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type CreateOneUseTokenParams struct {
	ID         string
	SecretHash []byte
	Sub        string
	TotpRev    int64
	ExpiresAt  string
	CreatedAt  string
}

func (q *Queries) CreateOneUseToken(ctx context.Context, arg CreateOneUseTokenParams) error {
	_, err := q.db.ExecContext(ctx, createOneUseToken,
		arg.ID,
		arg.SecretHash,
		arg.Sub,
		arg.TotpRev,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOneUseTokens = `-- name: DeleteExpiredOneUseTokens :exec
DELETE FROM one_use_tokens
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredOneUseTokens(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOneUseTokens, now)
	return err
}

const getOneUseToken = `-- name: GetOneUseToken :one
SELECT id, secret_hash, sub, totp_rev, expires_at, consumed_at, created_at
FROM one_use_tokens
WHERE id = ?1
`

func (q *Queries) GetOneUseToken(ctx context.Context, id string) (OneUseToken, error) {
	row := q.db.QueryRowContext(ctx, getOneUseToken, id)
	var i OneUseToken
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Sub,
		&i.TotpRev,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
