// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panic_locks.sql

package statestore

import (
	"context"
)

const clearPanicLock = `-- name: ClearPanicLock :exec
DELETE FROM panic_locks
WHERE sub = ?1
`

func (q *Queries) ClearPanicLock(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, clearPanicLock, sub)
	return err
}

const createPanicLock = `-- name: CreatePanicLock :exec
INSERT INTO panic_locks (sub, created_at)
VALUES (?1, ?2)
ON CONFLICT (sub) DO NOTHING
`

type CreatePanicLockParams struct {
	Sub       string
	CreatedAt string
}

func (q *Queries) CreatePanicLock(ctx context.Context, arg CreatePanicLockParams) error {
	_, err := q.db.ExecContext(ctx, createPanicLock, arg.Sub, arg.CreatedAt)
	return err
}

const getPanicLock = `-- name: GetPanicLock :one
SELECT sub, created_at
FROM panic_locks
WHERE sub = ?1
`

func (q *Queries) GetPanicLock(ctx context.Context, sub string) (PanicLock, error) {
	row := q.db.QueryRowContext(ctx, getPanicLock, sub)
	var i PanicLock
	err := row.Scan(&i.Sub, &i.CreatedAt)
	return i, err
}
