// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limit_counters.sql

package statestore

import (
	"context"
)

const createRateLimitCounter = `-- name: CreateRateLimitCounter :exec
INSERT INTO rate_limit_counters (key, attempts, reset_at, updated_at)
VALUES (?1, 1, ?2, ?3)
ON CONFLICT (key) DO NOTHING
`

type CreateRateLimitCounterParams struct {
	Key       string
	ResetAt   string
	UpdatedAt string
}

func (q *Queries) CreateRateLimitCounter(ctx context.Context, arg CreateRateLimitCounterParams) error {
	_, err := q.db.ExecContext(ctx, createRateLimitCounter, arg.Key, arg.ResetAt, arg.UpdatedAt)
	return err
}

const deleteExpiredRateLimitCounters = `-- name: DeleteExpiredRateLimitCounters :exec
DELETE FROM rate_limit_counters
WHERE reset_at < ?1
`

func (q *Queries) DeleteExpiredRateLimitCounters(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRateLimitCounters, now)
	return err
}

const getRateLimitCounter = `-- name: GetRateLimitCounter :one
SELECT key, attempts, reset_at, updated_at
FROM rate_limit_counters
WHERE key = ?1
`

func (q *Queries) GetRateLimitCounter(ctx context.Context, key string) (RateLimitCounter, error) {
	row := q.db.QueryRowContext(ctx, getRateLimitCounter, key)
	var i RateLimitCounter
	err := row.Scan(
		&i.Key,
		&i.Attempts,
		&i.ResetAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRateLimitCounter = `-- name: IncrementRateLimitCounter :exec
UPDATE rate_limit_counters
SET attempts = attempts + 1,
    updated_at = ?1
WHERE key = ?2
`

type IncrementRateLimitCounterParams struct {
	UpdatedAt string
	Key       string
}

func (q *Queries) IncrementRateLimitCounter(ctx context.Context, arg IncrementRateLimitCounterParams) error {
	_, err := q.db.ExecContext(ctx, incrementRateLimitCounter, arg.UpdatedAt, arg.Key)
	return err
}
