// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package statestore

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id,
    kind,
    secret_hash,
    sub,
    totp_rev,
    created_at,
    expires_at,
    ip_address,
    user_agent
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type CreateSessionParams struct {
	ID         string
	Kind       string
	SecretHash []byte
	Sub        string
	TotpRev    int64
	CreatedAt  string
	ExpiresAt  string
	IpAddress  sql.NullString
	UserAgent  sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Kind,
		arg.SecretHash,
		arg.Sub,
		arg.TotpRev,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, kind, secret_hash, sub, totp_rev, created_at, expires_at, ip_address, user_agent
FROM sessions
WHERE id = ?1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SecretHash,
		&i.Sub,
		&i.TotpRev,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM sessions
WHERE id = ?1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const revokeSessionsBySubject = `-- name: RevokeSessionsBySubject :exec
DELETE FROM sessions
WHERE sub = ?1
`

func (q *Queries) RevokeSessionsBySubject(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsBySubject, sub)
	return err
}
