package config

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"strings"
	"time"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

const (
	defaultMaxUserLoginAttempts    = 5
	defaultUserLoginAttemptsWindow = 5 * time.Minute
	defaultSessionMaxAge           = 72 * time.Hour
	defaultAuthorizationCodeMaxAge = 5 * time.Minute
	defaultIDTokenMaxAge           = 15 * time.Minute
	defaultAccessTokenMaxAge       = 15 * time.Minute
	defaultEnrollmentLinkMaxAge    = 5 * time.Minute
	maximumSubjectLength           = 255
)

// Protocol claims are generated by Zen IdP and cannot be supplied as custom
// user claims.
var reservedProtocolClaims = map[string]struct{}{
	// JWT registered claims defined by RFC 7519.
	"iss": {}, // Issuer.
	"sub": {}, // Subject, managed explicitly by Zen IdP.
	"aud": {}, // Audience.
	"exp": {}, // Expiration time.
	"iat": {}, // Issued-at time.
	"nbf": {}, // Not-before time.
	"jti": {}, // JWT identifier.

	// Claims defined by OpenID Connect Core 1.0.
	"nonce":     {}, // Value used to mitigate replay attacks.
	"auth_time": {}, // Time at which the user authenticated.
	"azp":       {}, // Authorized party.
	"at_hash":   {}, // Access token hash.
	"c_hash":    {}, // Authorization code hash.
	"acr":       {}, // Authentication context class reference.
	"amr":       {}, // Authentication methods references.
}

// configurationDocument represents the YAML envelope before defaults and
// normalized user values are resolved.
type configurationDocument struct {
	Settings settingsDocument `yaml:"config"`
	Clients  []Client         `yaml:"clients"`
	Users    []userDocument   `yaml:"users"`
}

// settingsDocument represents values nested below the YAML config field.
type settingsDocument struct {
	Issuer   string           `yaml:"issuer"`
	UI       uiDocument       `yaml:"ui"`
	Security securityDocument `yaml:"security"`
}

// uiDocument contains presentation settings from YAML.
type uiDocument struct {
	Name       string `yaml:"name"`
	LogoURL    string `yaml:"logo_url"`
	FaviconURL string `yaml:"favicon_url"`
}

// securityDocument contains unresolved security settings from YAML.
type securityDocument struct {
	AdminPasswordHash string             `yaml:"admin_password_hash"`
	RateLimits        rateLimitsDocument `yaml:"rate_limits"`
	Session           sessionDocument    `yaml:"session"`
	OIDC              oidcDocument       `yaml:"oidc"`
	Enrollment        enrollmentDocument `yaml:"enrollment"`
	TrustedProxies    []string           `yaml:"trusted_proxies"`
}

// rateLimitsDocument preserves omitted rate-limit values for defaulting.
type rateLimitsDocument struct {
	MaxUserLoginAttempts           *strictInt `yaml:"max_user_login_attempts"`
	UserLoginAttemptsWindowSeconds *strictInt `yaml:"user_login_attempts_window_seconds"`
}

// sessionDocument preserves an omitted SSO session lifetime for defaulting.
type sessionDocument struct {
	MaxAgeHours *strictInt `yaml:"max_age_hours"`
}

// oidcDocument preserves omitted OIDC artifact lifetimes for defaulting.
type oidcDocument struct {
	AuthorizationCodeMaxAgeSeconds *strictInt `yaml:"authorization_code_max_age_seconds"`
	IDTokenMaxAgeSeconds           *strictInt `yaml:"id_token_max_age_seconds"`
	AccessTokenMaxAgeSeconds       *strictInt `yaml:"access_token_max_age_seconds"`
}

// enrollmentDocument preserves an omitted enrollment lifetime for defaulting.
type enrollmentDocument struct {
	LinkMaxAgeSeconds *strictInt `yaml:"link_max_age_seconds"`
}

// strictInt rejects YAML values that are not explicitly represented as
// integers instead of accepting lossy numeric conversions.
type strictInt int

// userDocument decodes both supported YAML user declaration forms.
type userDocument struct {
	User User
}

// Parse decodes, defaults, and validates one Zen IdP YAML document.
func Parse(contents []byte) (*Configuration, error) {
	decoder := yaml.NewDecoder(bytes.NewReader(contents))
	decoder.KnownFields(true)
	var document configurationDocument
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("decode configuration: %w", err)
	}
	var extra yaml.Node
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err != nil {
			return nil, fmt.Errorf("decode configuration: %w", err)
		}
		return nil, errors.New("decode configuration: multiple YAML documents are not supported")
	}

	configuration := resolve(document)
	if err := validate(configuration); err != nil {
		return nil, err
	}

	return configuration, nil
}

// UnmarshalYAML normalizes shorthand and long-form YAML user declarations.
func (document *userDocument) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind == yaml.ScalarNode {
		if node.Tag != "!!str" {
			return fmt.Errorf(
				"decode shorthand user at line %d: subject must be a string",
				node.Line,
			)
		}
		var subject string
		if err := node.Decode(&subject); err != nil {
			return fmt.Errorf("decode shorthand user: %w", err)
		}
		document.User = User{
			Subject: subject,
			Login:   subject,
			Claims:  make(map[string]any),
		}
		return nil
	}
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf(
			"decode user at line %d: declaration must be a string or mapping",
			node.Line,
		)
	}

	user := User{Claims: make(map[string]any)}
	loginWasSet := false
	for index := 0; index < len(node.Content); index += 2 {
		key := node.Content[index].Value
		value := node.Content[index+1]
		switch key {
		case "sub":
			if value.Tag != "!!str" {
				return fmt.Errorf("decode user sub at line %d: value must be a string", value.Line)
			}
			if err := value.Decode(&user.Subject); err != nil {
				return fmt.Errorf("decode user sub at line %d: %w", value.Line, err)
			}
		case "idp_login":
			if value.Tag != "!!str" {
				return fmt.Errorf(
					"decode user idp_login at line %d: value must be a string",
					value.Line,
				)
			}
			if err := value.Decode(&user.Login); err != nil {
				return fmt.Errorf("decode user idp_login at line %d: %w", value.Line, err)
			}
			loginWasSet = true
		case "idp_totp_rev":
			if value.Tag != "!!int" {
				return fmt.Errorf(
					"decode user idp_totp_rev at line %d: value must be a non-negative integer",
					value.Line,
				)
			}
			if err := value.Decode(&user.TOTPRevision); err != nil {
				return fmt.Errorf("decode user idp_totp_rev at line %d: %w", value.Line, err)
			}
		case "idp_expires_at":
			if value.Tag != "!!str" {
				return fmt.Errorf(
					"decode user idp_expires_at at line %d: value must be an RFC3339 string",
					value.Line,
				)
			}
			var expiresAt string
			if err := value.Decode(&expiresAt); err != nil {
				return fmt.Errorf("decode user idp_expires_at at line %d: %w", value.Line, err)
			}
			parsedExpiresAt, err := time.Parse(time.RFC3339, expiresAt)
			if err != nil {
				return fmt.Errorf(
					"decode user idp_expires_at at line %d: value must use RFC3339 format: %w",
					value.Line,
					err,
				)
			}
			user.ExpiresAt = parsedExpiresAt
		default:
			if strings.HasPrefix(key, "idp_") {
				return fmt.Errorf(
					"decode user at line %d: unsupported reserved field %q",
					value.Line,
					key,
				)
			}
			if _, reserved := reservedProtocolClaims[key]; reserved {
				return fmt.Errorf("decode user at line %d: claim %q is reserved", value.Line, key)
			}
			var claim any
			if err := value.Decode(&claim); err != nil {
				return fmt.Errorf("decode user claim %q at line %d: %w", key, value.Line, err)
			}
			if err := validateClaimValue(claim); err != nil {
				return fmt.Errorf("decode user claim %q at line %d: %w", key, value.Line, err)
			}
			user.Claims[key] = claim
		}
	}
	if !loginWasSet {
		user.Login = user.Subject
	}

	document.User = user
	return nil
}

// UnmarshalYAML decodes only YAML integer scalars into a strictInt.
func (value *strictInt) UnmarshalYAML(node *yaml.Node) error {
	if node.Tag != "!!int" {
		return fmt.Errorf("value at line %d must be an integer", node.Line)
	}
	var decoded int
	if err := node.Decode(&decoded); err != nil {
		return fmt.Errorf("decode integer at line %d: %w", node.Line, err)
	}
	*value = strictInt(decoded)
	return nil
}

// resolve converts the YAML document into the public runtime model and applies
// defaults to every omitted setting.
func resolve(document configurationDocument) *Configuration {
	settings := document.Settings
	configuration := &Configuration{
		Issuer: settings.Issuer,
		UI: UI{
			Name:       settings.UI.Name,
			LogoURL:    settings.UI.LogoURL,
			FaviconURL: settings.UI.FaviconURL,
		},
		Security: Security{
			AdminPasswordHash: settings.Security.AdminPasswordHash,
			RateLimits: RateLimits{
				MaxUserLoginAttempts: intValue(
					settings.Security.RateLimits.MaxUserLoginAttempts,
					defaultMaxUserLoginAttempts,
				),
				UserLoginAttemptsWindow: durationValue(
					settings.Security.RateLimits.UserLoginAttemptsWindowSeconds,
					defaultUserLoginAttemptsWindow,
					time.Second,
				),
			},
			Session: Session{
				MaxAge: durationValue(
					settings.Security.Session.MaxAgeHours,
					defaultSessionMaxAge,
					time.Hour,
				),
			},
			OIDC: OIDC{
				AuthorizationCodeMaxAge: durationValue(
					settings.Security.OIDC.AuthorizationCodeMaxAgeSeconds,
					defaultAuthorizationCodeMaxAge,
					time.Second,
				),
				IDTokenMaxAge: durationValue(
					settings.Security.OIDC.IDTokenMaxAgeSeconds,
					defaultIDTokenMaxAge,
					time.Second,
				),
				AccessTokenMaxAge: durationValue(
					settings.Security.OIDC.AccessTokenMaxAgeSeconds,
					defaultAccessTokenMaxAge,
					time.Second,
				),
			},
			Enrollment: Enrollment{
				LinkMaxAge: durationValue(
					settings.Security.Enrollment.LinkMaxAgeSeconds,
					defaultEnrollmentLinkMaxAge,
					time.Second,
				),
			},
			TrustedProxies: append([]string{}, settings.Security.TrustedProxies...),
		},
		Clients: append([]Client{}, document.Clients...),
		Users:   make([]User, 0, len(document.Users)),
	}
	for _, user := range document.Users {
		configuration.Users = append(configuration.Users, user.User)
	}

	return configuration
}

// intValue returns a configured integer or its default when omitted.
func intValue(value *strictInt, defaultValue int) int {
	if value == nil {
		return defaultValue
	}
	return int(*value)
}

// durationValue converts a configured unit count to a duration or returns its
// default when omitted.
func durationValue(value *strictInt, defaultValue, unit time.Duration) time.Duration {
	if value == nil {
		return defaultValue
	}
	return time.Duration(*value) * unit
}

// validate checks invariants required by consumers of the resolved model.
func validate(configuration *Configuration) error {
	if configuration.Issuer == "" {
		return fmt.Errorf("validate configuration: config.issuer is required")
	}
	if configuration.Security.AdminPasswordHash == "" {
		return fmt.Errorf("validate configuration: config.security.admin_password_hash is required")
	}
	if configuration.Security.RateLimits.MaxUserLoginAttempts <= 0 {
		return fmt.Errorf(
			"validate configuration: config.security.rate_limits.max_user_login_attempts must be positive",
		)
	}
	if configuration.Security.RateLimits.UserLoginAttemptsWindow <= 0 {
		return fmt.Errorf(
			"validate configuration: config.security.rate_limits.user_login_attempts_window_seconds must be positive",
		)
	}
	if configuration.Security.Session.MaxAge <= 0 {
		return fmt.Errorf(
			"validate configuration: config.security.session.max_age_hours must be positive",
		)
	}
	if configuration.Security.OIDC.AuthorizationCodeMaxAge <= 0 ||
		configuration.Security.OIDC.IDTokenMaxAge <= 0 ||
		configuration.Security.OIDC.AccessTokenMaxAge <= 0 {
		return fmt.Errorf("validate configuration: config.security.oidc lifetimes must be positive")
	}
	if configuration.Security.Enrollment.LinkMaxAge <= 0 {
		return fmt.Errorf(
			"validate configuration: config.security.enrollment.link_max_age_seconds must be positive",
		)
	}
	if err := validateClients(configuration.Clients); err != nil {
		return err
	}
	return validateUsers(configuration.Users)
}

// validateClients checks required confidential-client fields.
func validateClients(clients []Client) error {
	identifiers := make(map[string]int, len(clients))
	for index, client := range clients {
		if client.ID == "" {
			return fmt.Errorf("validate configuration: clients[%d].client_id is required", index)
		}
		if first, exists := identifiers[client.ID]; exists {
			return fmt.Errorf(
				"validate configuration: client_id %q duplicates clients[%d]",
				client.ID,
				first,
			)
		}
		identifiers[client.ID] = index
		if client.SecretHash == "" {
			return fmt.Errorf(
				"validate configuration: client %q secret_hash is required",
				client.ID,
			)
		}
		if len(client.RedirectURIs) == 0 {
			return fmt.Errorf(
				"validate configuration: client %q requires at least one redirect_uri",
				client.ID,
			)
		}
	}
	return nil
}

// validateUsers checks subject constraints and the shared identity/login
// namespace required by the specification.
func validateUsers(users []User) error {
	identifiers := make(map[string]int, len(users)*2)
	for index, user := range users {
		if user.Subject == "" {
			return fmt.Errorf("validate configuration: users[%d].sub is required", index)
		}
		if len(user.Subject) > maximumSubjectLength || !isASCII(user.Subject) {
			return fmt.Errorf(
				"validate configuration: user sub %q must contain at most 255 ASCII characters",
				user.Subject,
			)
		}

		if user.Login == "" {
			return fmt.Errorf(
				"validate configuration: user %q has an empty effective login",
				user.Subject,
			)
		}

		if first, exists := identifiers[user.Subject]; exists && first != index {
			return fmt.Errorf(
				"validate configuration: user identifier %q conflicts with users[%d]",
				user.Subject,
				first,
			)
		}
		identifiers[user.Subject] = index

		if first, exists := identifiers[user.Login]; exists && first != index {
			return fmt.Errorf(
				"validate configuration: user login %q conflicts with users[%d]",
				user.Login,
				first,
			)
		}
		identifiers[user.Login] = index
	}
	return nil
}

// isASCII reports whether text consists only of ASCII bytes and valid UTF-8.
func isASCII(text string) bool {
	if !utf8.ValidString(text) {
		return false
	}
	for _, character := range text {
		if character > 127 {
			return false
		}
	}
	return true
}

// validateClaimValue rejects YAML values that cannot be represented faithfully
// as JSON claims.
func validateClaimValue(value any) error {
	switch typed := value.(type) {
	case nil, bool, string, int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
		return nil
	case float32:
		if math.IsNaN(float64(typed)) || math.IsInf(float64(typed), 0) {
			return fmt.Errorf("value must be a finite JSON number")
		}
		return nil
	case float64:
		if math.IsNaN(typed) || math.IsInf(typed, 0) {
			return fmt.Errorf("value must be a finite JSON number")
		}
		return nil
	case []any:
		for _, item := range typed {
			if err := validateClaimValue(item); err != nil {
				return err
			}
		}
		return nil
	case map[string]any:
		for _, item := range typed {
			if err := validateClaimValue(item); err != nil {
				return err
			}
		}
		return nil
	default:
		return fmt.Errorf("value of type %T is not JSON-compatible", value)
	}
}
