package config

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"strings"
	"time"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

const (
	defaultServerHost               = "127.0.0.1"
	defaultServerPort               = 8080
	defaultMaxUserLoginAttempts     = 5
	defaultUserLoginAttemptsWindow  = 5 * time.Minute
	defaultMaxClientAuthAttempts    = 5
	defaultClientAuthAttemptsWindow = 5 * time.Minute
	defaultSessionMaxAge            = 72 * time.Hour
	maximumUserLoginAttempts        = 100
	maximumUserLoginAttemptsWindow  = 24 * time.Hour
	maximumClientAuthAttempts       = 100
	maximumClientAuthAttemptsWindow = 24 * time.Hour
	maximumSessionMaxAge            = 365 * 24 * time.Hour
	maximumSubjectLength            = 255
)

// Protocol claims are generated by Zen IdP and cannot be supplied as custom
// user claims.
var reservedProtocolClaims = map[string]struct{}{
	// JWT registered claims defined by RFC 7519.
	"iss": {}, // Issuer.
	"sub": {}, // Subject, managed explicitly by Zen IdP.
	"aud": {}, // Audience.
	"exp": {}, // Expiration time.
	"iat": {}, // Issued-at time.
	"nbf": {}, // Not-before time.
	"jti": {}, // JWT identifier.

	// Claims defined by OpenID Connect Core 1.0.
	"nonce":     {}, // Value used to mitigate replay attacks.
	"auth_time": {}, // Time at which the user authenticated.
	"azp":       {}, // Authorized party.
	"at_hash":   {}, // Access token hash.
	"c_hash":    {}, // Authorization code hash.
	"acr":       {}, // Authentication context class reference.
	"amr":       {}, // Authentication methods references.
}

// configurationDocument represents the YAML envelope before defaults and
// normalized user values are resolved.
type configurationDocument struct {
	Settings settingsDocument `yaml:"config"`
	Clients  []clientDocument `yaml:"clients"`
	Users    []userDocument   `yaml:"users"`
}

// settingsDocument represents values nested below the YAML config field.
type settingsDocument struct {
	Issuer   strictString     `yaml:"issuer"`
	Server   serverDocument   `yaml:"server"`
	UI       uiDocument       `yaml:"ui"`
	Security securityDocument `yaml:"security"`
}

// serverDocument contains HTTP listener settings from YAML.
type serverDocument struct {
	Host optionalString `yaml:"host"`
	Port optionalInt    `yaml:"port"`
}

// uiDocument contains presentation settings from YAML.
type uiDocument struct {
	Name       optionalString `yaml:"name"`
	LogoURL    optionalString `yaml:"logo_url"`
	FaviconURL optionalString `yaml:"favicon_url"`
}

// clientDocument contains one OIDC client from YAML.
type clientDocument struct {
	ID           strictString   `yaml:"id"`
	Name         strictString   `yaml:"name"`
	SecretHash   optionalString `yaml:"secret_hash"`
	RedirectURIs []strictString `yaml:"redirect_uris"`
}

// securityDocument contains unresolved security settings from YAML.
type securityDocument struct {
	AdminPasswordHash strictString       `yaml:"admin_password_hash"`
	RateLimits        rateLimitsDocument `yaml:"rate_limits"`
	Session           sessionDocument    `yaml:"session"`
}

// rateLimitsDocument preserves omitted rate-limit values for defaulting.
type rateLimitsDocument struct {
	MaxUserLoginAttempts            optionalInt `yaml:"max_user_login_attempts"`
	UserLoginAttemptsWindowSeconds  optionalInt `yaml:"user_login_attempts_window_seconds"`
	MaxClientAuthAttempts           optionalInt `yaml:"max_client_auth_attempts"`
	ClientAuthAttemptsWindowSeconds optionalInt `yaml:"client_auth_attempts_window_seconds"`
}

// sessionDocument preserves an omitted SSO session lifetime for defaulting.
type sessionDocument struct {
	MaxAgeHours optionalInt `yaml:"max_age_hours"`
}

// strictInt rejects YAML values that are not explicitly represented as
// integers instead of accepting lossy numeric conversions.
type strictInt int

// strictString rejects YAML values that are not explicitly represented as
// strings.
type strictString string

// optionalInt distinguishes an omitted integer from a present value.
type optionalInt struct {
	Value strictInt
	Set   bool
}

// optionalString distinguishes an omitted string from a present value.
type optionalString struct {
	Value strictString
	Set   bool
}

// userDocument decodes a structured YAML user declaration.
type userDocument struct {
	User User
}

// Parse decodes, defaults, and validates one Zen IdP YAML document.
func Parse(contents []byte) (*Config, error) {
	decoder := yaml.NewDecoder(bytes.NewReader(contents))
	decoder.KnownFields(true)
	var document configurationDocument
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("decode configuration: %w", err)
	}
	var extra yaml.Node
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err != nil {
			return nil, fmt.Errorf("decode configuration: %w", err)
		}
		return nil, errors.New("decode configuration: multiple YAML documents are not supported")
	}
	if err := rejectExplicitNulls(contents); err != nil {
		return nil, err
	}
	if err := validateDocument(document); err != nil {
		return nil, err
	}

	configuration := resolve(document)
	if err := validate(configuration); err != nil {
		return nil, err
	}

	return configuration, nil
}

// UnmarshalYAML decodes one structured YAML user declaration.
func (document *userDocument) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("decode user at line %d: declaration must be a mapping", node.Line)
	}

	user := User{Claims: make(map[string]any)}
	loginWasSet := false
	seenFields := make(map[string]struct{}, len(node.Content)/2)
	for index := 0; index < len(node.Content); index += 2 {
		keyNode := node.Content[index]
		if keyNode.Tag != "!!str" {
			return fmt.Errorf("decode user field at line %d: key must be a string", keyNode.Line)
		}
		key := keyNode.Value
		if _, duplicate := seenFields[key]; duplicate {
			return fmt.Errorf("decode user at line %d: field %q is duplicated", keyNode.Line, key)
		}
		seenFields[key] = struct{}{}
		value := node.Content[index+1]
		switch key {
		case "sub":
			if value.Tag != "!!str" {
				return fmt.Errorf("decode user sub at line %d: value must be a string", value.Line)
			}
			if err := value.Decode(&user.Subject); err != nil {
				return fmt.Errorf("decode user sub at line %d: %w", value.Line, err)
			}
		case "idp_login":
			if value.Tag != "!!str" {
				return fmt.Errorf(
					"decode user idp_login at line %d: value must be a string",
					value.Line,
				)
			}
			if err := value.Decode(&user.Login); err != nil {
				return fmt.Errorf("decode user idp_login at line %d: %w", value.Line, err)
			}
			loginWasSet = true
		case "idp_totp_rev":
			if value.Tag != "!!int" {
				return fmt.Errorf(
					"decode user idp_totp_rev at line %d: value must be a non-negative integer",
					value.Line,
				)
			}
			if err := value.Decode(&user.TOTPRevision); err != nil {
				return fmt.Errorf("decode user idp_totp_rev at line %d: %w", value.Line, err)
			}
		case "idp_expires_at":
			if value.Tag != "!!str" {
				return fmt.Errorf(
					"decode user idp_expires_at at line %d: value must be an RFC3339 string",
					value.Line,
				)
			}
			var expiresAt string
			if err := value.Decode(&expiresAt); err != nil {
				return fmt.Errorf("decode user idp_expires_at at line %d: %w", value.Line, err)
			}
			parsedExpiresAt, err := time.Parse(time.RFC3339, expiresAt)
			if err != nil {
				return fmt.Errorf(
					"decode user idp_expires_at at line %d: value must use RFC3339 format: %w",
					value.Line,
					err,
				)
			}
			user.ExpiresAt = parsedExpiresAt
		default:
			if strings.HasPrefix(key, "idp_") {
				return fmt.Errorf(
					"decode user at line %d: unsupported reserved field %q",
					value.Line,
					key,
				)
			}
			if _, reserved := reservedProtocolClaims[key]; reserved {
				return fmt.Errorf("decode user at line %d: claim %q is reserved", value.Line, key)
			}
			var claim any
			if err := value.Decode(&claim); err != nil {
				return fmt.Errorf("decode user claim %q at line %d: %w", key, value.Line, err)
			}
			if err := validateClaimValue(claim); err != nil {
				return fmt.Errorf("decode user claim %q at line %d: %w", key, value.Line, err)
			}
			user.Claims[key] = claim
		}
	}
	if !loginWasSet {
		user.Login = user.Subject
	}

	document.User = user
	return nil
}

// UnmarshalYAML decodes only YAML integer scalars into a strictInt.
func (value *strictInt) UnmarshalYAML(node *yaml.Node) error {
	if node.Tag != "!!int" {
		return fmt.Errorf("value at line %d must be an integer", node.Line)
	}
	var decoded int
	if err := node.Decode(&decoded); err != nil {
		return fmt.Errorf("decode integer at line %d: %w", node.Line, err)
	}
	*value = strictInt(decoded)
	return nil
}

// UnmarshalYAML decodes only YAML string scalars into a strictString.
func (value *strictString) UnmarshalYAML(node *yaml.Node) error {
	if node.Tag != "!!str" {
		return fmt.Errorf("value at line %d must be a string", node.Line)
	}
	*value = strictString(node.Value)
	return nil
}

// UnmarshalYAML records and decodes one explicitly configured integer.
func (value *optionalInt) UnmarshalYAML(node *yaml.Node) error {
	value.Set = true
	return value.Value.UnmarshalYAML(node)
}

// UnmarshalYAML records and decodes one explicitly configured string.
func (value *optionalString) UnmarshalYAML(node *yaml.Node) error {
	value.Set = true
	return value.Value.UnmarshalYAML(node)
}

// resolve converts the YAML document into the public runtime model and applies
// defaults to every omitted setting.
func resolve(document configurationDocument) *Config {
	settings := document.Settings
	configuration := &Config{
		Issuer: string(settings.Issuer),
		Server: Server{
			Host: stringValue(settings.Server.Host, defaultServerHost),
			Port: intValue(settings.Server.Port, defaultServerPort),
		},
		UI: UI{
			Name:       stringValue(settings.UI.Name, ""),
			LogoURL:    stringValue(settings.UI.LogoURL, ""),
			FaviconURL: stringValue(settings.UI.FaviconURL, ""),
		},
		Security: Security{
			AdminPasswordHash: string(settings.Security.AdminPasswordHash),
			RateLimits: RateLimits{
				MaxUserLoginAttempts: intValue(
					settings.Security.RateLimits.MaxUserLoginAttempts,
					defaultMaxUserLoginAttempts,
				),
				UserLoginAttemptsWindow: durationValue(
					settings.Security.RateLimits.UserLoginAttemptsWindowSeconds,
					defaultUserLoginAttemptsWindow,
					time.Second,
				),
				MaxClientAuthAttempts: intValue(
					settings.Security.RateLimits.MaxClientAuthAttempts,
					defaultMaxClientAuthAttempts,
				),
				ClientAuthAttemptsWindow: durationValue(
					settings.Security.RateLimits.ClientAuthAttemptsWindowSeconds,
					defaultClientAuthAttemptsWindow,
					time.Second,
				),
			},
			Session: Session{
				MaxAge: durationValue(
					settings.Security.Session.MaxAgeHours,
					defaultSessionMaxAge,
					time.Hour,
				),
			},
		},
		Clients: make([]Client, 0, len(document.Clients)),
		Users:   make([]User, 0, len(document.Users)),
	}
	for _, client := range document.Clients {
		name := string(client.Name)
		if name == "" {
			name = string(client.ID)
		}
		configuration.Clients = append(configuration.Clients, Client{
			ID:           string(client.ID),
			Name:         name,
			SecretHash:   stringValue(client.SecretHash, ""),
			RedirectURIs: strictStrings(client.RedirectURIs),
		})
	}
	for _, user := range document.Users {
		configuration.Users = append(configuration.Users, user.User)
	}

	return configuration
}

// stringValue returns a configured string or its default when omitted.
func stringValue(value optionalString, defaultValue string) string {
	if !value.Set {
		return defaultValue
	}
	return string(value.Value)
}

// strictStrings converts parsed YAML strings into their runtime representation.
func strictStrings(values []strictString) []string {
	result := make([]string, len(values))
	for index, value := range values {
		result[index] = string(value)
	}
	return result
}

// intValue returns a configured integer or its default when omitted.
func intValue(value optionalInt, defaultValue int) int {
	if !value.Set {
		return defaultValue
	}
	return int(value.Value)
}

// durationValue converts a configured unit count to a duration or returns its
// default when omitted.
func durationValue(value optionalInt, defaultValue, unit time.Duration) time.Duration {
	if !value.Set {
		return defaultValue
	}
	return time.Duration(value.Value) * unit
}

// validate checks invariants required by consumers of the resolved model.
func validate(configuration *Config) error {
	if configuration.Issuer == "" {
		return fmt.Errorf("validate configuration: config.issuer is required")
	}
	if err := validateIssuerURL(configuration.Issuer); err != nil {
		return fmt.Errorf("validate configuration: config.issuer: %w", err)
	}
	if strings.TrimSpace(configuration.Server.Host) == "" {
		return fmt.Errorf("validate configuration: config.server.host must not be empty")
	}
	if configuration.Server.Port <= 0 || configuration.Server.Port > 65535 {
		return fmt.Errorf("validate configuration: config.server.port must be between 1 and 65535")
	}
	if configuration.Security.AdminPasswordHash == "" {
		return fmt.Errorf("validate configuration: config.security.admin_password_hash is required")
	}
	if err := validateArgon2idHash(configuration.Security.AdminPasswordHash); err != nil {
		return fmt.Errorf(
			"validate configuration: config.security.admin_password_hash: %w",
			err,
		)
	}
	if err := validateUI(configuration.UI); err != nil {
		return err
	}
	if configuration.Security.RateLimits.MaxUserLoginAttempts <= 0 ||
		configuration.Security.RateLimits.MaxUserLoginAttempts > maximumUserLoginAttempts {
		return fmt.Errorf(
			"validate configuration: config.security.rate_limits.max_user_login_attempts must be between 1 and 100",
		)
	}
	if configuration.Security.RateLimits.UserLoginAttemptsWindow <= 0 ||
		configuration.Security.RateLimits.UserLoginAttemptsWindow > maximumUserLoginAttemptsWindow {
		return fmt.Errorf(
			"validate configuration: config.security.rate_limits.user_login_attempts_window_seconds must be between 1 and 86400",
		)
	}
	if configuration.Security.RateLimits.MaxClientAuthAttempts <= 0 ||
		configuration.Security.RateLimits.MaxClientAuthAttempts > maximumClientAuthAttempts {
		return fmt.Errorf(
			"validate configuration: config.security.rate_limits.max_client_auth_attempts must be between 1 and 100",
		)
	}
	if configuration.Security.RateLimits.ClientAuthAttemptsWindow <= 0 ||
		configuration.Security.RateLimits.ClientAuthAttemptsWindow > maximumClientAuthAttemptsWindow {
		return fmt.Errorf(
			"validate configuration: config.security.rate_limits.client_auth_attempts_window_seconds must be between 1 and 86400",
		)
	}
	if configuration.Security.Session.MaxAge <= 0 ||
		configuration.Security.Session.MaxAge > maximumSessionMaxAge {
		return fmt.Errorf(
			"validate configuration: config.security.session.max_age_hours must be between 1 and 8760",
		)
	}
	if err := validateClients(configuration.Clients); err != nil {
		return err
	}
	return validateUsers(configuration.Users)
}

// validateClients checks required client fields.
func validateClients(clients []Client) error {
	identifiers := make(map[string]int, len(clients))
	for index, client := range clients {
		if strings.TrimSpace(client.ID) == "" {
			return fmt.Errorf("validate configuration: clients[%d].id is required", index)
		}
		if first, exists := identifiers[client.ID]; exists {
			return fmt.Errorf(
				"validate configuration: client id %q duplicates clients[%d]",
				client.ID,
				first,
			)
		}
		identifiers[client.ID] = index
		if client.Name != "" && strings.TrimSpace(client.Name) == "" {
			return fmt.Errorf("validate configuration: client %q name must not be blank", client.ID)
		}
		if len(client.RedirectURIs) == 0 {
			return fmt.Errorf(
				"validate configuration: client %q requires at least one redirect_uri",
				client.ID,
			)
		}
		if client.SecretHash != "" {
			if err := validateArgon2idHash(client.SecretHash); err != nil {
				return fmt.Errorf(
					"validate configuration: client %q secret_hash: %w",
					client.ID,
					err,
				)
			}
		}
		if err := validateRedirectURIs(client); err != nil {
			return err
		}
	}
	return nil
}

// validateUsers checks subject constraints and the shared identity/login
// namespace.
func validateUsers(users []User) error {
	identifiers := make(map[string]int, len(users)*2)
	for index, user := range users {
		if user.Subject == "" {
			return fmt.Errorf("validate configuration: users[%d].sub is required", index)
		}
		if len(user.Subject) > maximumSubjectLength || !isASCII(user.Subject) {
			return fmt.Errorf(
				"validate configuration: user sub %q must contain at most 255 ASCII characters",
				user.Subject,
			)
		}

		if user.Login == "" {
			return fmt.Errorf(
				"validate configuration: user %q idp_login must not be empty",
				user.Subject,
			)
		}

		// One user may own the same value as both identifiers; only another owner
		// creates a namespace collision.
		if first, exists := identifiers[user.Subject]; exists && first != index {
			return fmt.Errorf(
				"validate configuration: user identifier %q conflicts with users[%d]",
				user.Subject,
				first,
			)
		}
		identifiers[user.Subject] = index

		if first, exists := identifiers[user.Login]; exists && first != index {
			return fmt.Errorf(
				"validate configuration: user login %q conflicts with users[%d]",
				user.Login,
				first,
			)
		}
		identifiers[user.Login] = index
	}
	return nil
}

// isASCII reports whether text consists only of ASCII bytes and valid UTF-8.
func isASCII(text string) bool {
	if !utf8.ValidString(text) {
		return false
	}
	for _, character := range text {
		if character > 127 {
			return false
		}
	}
	return true
}

// validateClaimValue rejects YAML values that cannot be represented faithfully
// as JSON claims.
func validateClaimValue(value any) error {
	switch typed := value.(type) {
	case nil, bool, string, int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
		return nil
	case float32:
		if math.IsNaN(float64(typed)) || math.IsInf(float64(typed), 0) {
			return fmt.Errorf("value must be a finite JSON number")
		}
		return nil
	case float64:
		if math.IsNaN(typed) || math.IsInf(typed, 0) {
			return fmt.Errorf("value must be a finite JSON number")
		}
		return nil
	case []any:
		for _, item := range typed {
			if err := validateClaimValue(item); err != nil {
				return err
			}
		}
		return nil
	case map[string]any:
		for _, item := range typed {
			if err := validateClaimValue(item); err != nil {
				return err
			}
		}
		return nil
	default:
		return fmt.Errorf("value of type %T is not JSON-compatible", value)
	}
}
